// Generated by CoffeeScript 1.6.3
var Set, regexpGolf;

Set = require('../src/set');

regexpGolf = require('../src/regexpGolf.coffee');

exports.RegExpGolfTest = {
  'test can find regexp with default options': function(test) {
    var loser, losers, regexp, result, winner, winners, _i, _j, _len, _len1, _ref, _ref1;
    winners = new Set(['one', 'two', 'three']);
    losers = new Set(['four', 'five', 'six']);
    result = regexpGolf.find(winners, losers);
    test.ok(result.length === 1, 'one regexp returned with default options');
    test.equals(result[0].length, 4, 'expression should be short: #{result[0]}');
    regexp = new RegExp(result[0]);
    _ref = winners.arr;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      winner = _ref[_i];
      test.ok(regexp.test(winner), "" + regexp + ": winner " + winner + " matched");
    }
    _ref1 = losers.arr;
    for (_j = 0, _len1 = _ref1.length; _j < _len1; _j++) {
      loser = _ref1[_j];
      test.ok(!regexp.test(loser), "" + regexp + ": loser " + loser + " not matched");
    }
    return test.done();
  }
};
